name: Build Executable with PyInstaller

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          python_arch: 'x86'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'ExcelTool-Win'
          options: --onefile, --name "ExcelTool-Win", -c,

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          python_arch: 'x64'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'ExcelTool-Win64'
          options: --onefile, --name "ExcelTool-Win64", -c,

  pyinstaller-build-mac:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'ExcelTool-Mac'
          options: --onefile, --name "ExcelTool-Mac", -c,
