name: Build Executable with PyInstaller

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'excel.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'ExcelTool'
          options: --onefile, --name "ExcelTool", -c,
